version: '3'
services:
  goauth:
    build: .
    restart: always
    ports:
     - "8080:8080"
    environment:
      CONNECTION_STRING: postgres://postgres:password@postgres/goauth?sslmode=disable
    depends_on:
      - postgres
  postgres:
    build:
      context: ./
      dockerfile: Dockerfile-postgres-test
    restart: always
    environment:
      POSTGRES_PASSWORD: password